In [5]:
#Import necessary modules
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

df = pd.read_csv("kecemasan1.csv", sep=";")
#print(df)

# Create feature and target arrays
X = df[['K1','K2','K3','K4','K5','K6','K7']]
y = df['tingkat_kecemasan']
  
# Split into training and test set
X_train, X_test, y_train, y_test = train_test_split(
             X, y, test_size = 0.2, random_state=42)
print(y_test)
  
knn = KNeighborsClassifier(n_neighbors=7)
  
knn.fit(X_train, y_train)

# Predicting the Test set results
y_pred = knn.predict(X_test)
print('Hasil Prediksi:')
#print(knn.predict(X_test))
print(y_pred)
#np.array(y_pred) 

# membuat confusion matrix
confusion_matrix(y_test, y_pred)
print('Confusion Matrix:')
print(confusion_matrix(y_test, y_pred))

#evaluate performance from the confusion matrix 
from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(y_test, y_pred))
  
# Calculate the accuracy of the model
print('akurasi: ')
print(knn.score(X_test, y_test))

83          Normal
53          Normal
70    Sangat Berat
45          Sedang
44           Berat
39          Normal
22    Sangat Berat
80           Berat
10          Sedang
0           Sedang
18           Berat
30    Sangat Berat
73          Sedang
33          Normal
90           Berat
4           Normal
76          Normal
77          Sedang
12          Sedang
31          Sedang
Name: tingkat_kecemasan, dtype: object
Hasil Prediksi:
['Normal' 'Normal' 'Berat' 'Sedang' 'Sedang' 'Normal' 'Sangat Berat'
 'Berat' 'Sedang' 'Berat' 'Berat' 'Sangat Berat' 'Berat' 'Normal' 'Sedang'
 'Normal' 'Normal' 'Berat' 'Sedang' 'Sedang']
Confusion Matrix:
[[2 0 0 2]
 [0 6 0 0]
 [1 0 2 0]
 [3 0 0 4]]
              precision    recall  f1-score   support

       Berat       0.33      0.50      0.40         4
      Normal       1.00      1.00      1.00         6
Sangat Berat       1.00      0.67      0.80         3
      Sedang       0.67      0.57      0.62         7

    accuracy                           0