In [2]:
#Import necessary modules
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

df = pd.read_csv("stress1.csv", sep=";")
#print(df)

# Create feature and target arrays
X = df[['S1','S2','S3','S4','S5','S6','S7']]
y = df['tingkat_stres']
  
# Split into training and test set
X_train, X_test, y_train, y_test = train_test_split(
             X, y, test_size = 0.2, random_state=42)
  
knn = KNeighborsClassifier(n_neighbors=7)
  
knn.fit(X_train, y_train)

# Predicting the Test set results
y_pred = knn.predict(X_test)
print('Hasil Prediksi:')
print(knn.predict(X_test))

# membuat confusion matrix
confusion_matrix(y_test, y_pred)
print('Confusion Matrix:')
print(confusion_matrix(y_test, y_pred))
  
# Calculate the accuracy of the model
print('akurasi: ')
print(knn.score(X_test, y_test))

Hasil Prediksi:
['Ringan' 'Normal' 'Berat' 'Normal' 'Normal' 'Normal' 'Ringan' 'Ringan'
 'Sedang' 'Ringan' 'Normal' 'Sedang' 'Normal' 'Normal' 'Ringan' 'Normal'
 'Normal' 'Sedang' 'Sedang' 'Normal']
Confusion Matrix:
[[1 0 0 0]
 [0 9 0 0]
 [0 1 5 2]
 [0 0 0 2]]
akurasi: 
0.85
