In [1]:
#Import necessary modules
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

df = pd.read_csv("depresi1.csv", sep=";")
#print(df)

# Create feature and target arrays
X = df[['D1','D2','D3','D4','D5','D6','D7']]
y = df['tingkat_depresi']
  
# Split into training and test set
X_train, X_test, y_train, y_test = train_test_split(
             X, y, test_size = 0.2, random_state=42)

print(y_test)
  
knn = KNeighborsClassifier(n_neighbors=7)
  
knn.fit(X_train, y_train)

# Predicting the Test set results
y_pred = knn.predict(X_test)
print('Hasil Prediksi:')
print(knn.predict(X_test))

# membuat confusion matrix
confusion_matrix(y_test, y_pred)
print('Confusion Matrix:')
print(confusion_matrix(y_test, y_pred))

#evaluate performance from the confusion matrix 
from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(y_test, y_pred))
  
# Calculate the accuracy of the model
print('akurasi: ')
print(knn.score(X_test, y_test))

83    Ringan
53    Normal
70    Sedang
45    Normal
44    Normal
39    Normal
22    Sedang
80    Ringan
10    Ringan
0     Ringan
18    Normal
30    Sedang
73    Normal
33    Normal
90    Normal
4     Normal
76    Normal
77    Sedang
12    Normal
31    Normal
Name: tingkat_depresi, dtype: object
Hasil Prediksi:
['Normal' 'Normal' 'Sedang' 'Normal' 'Normal' 'Normal' 'Sedang' 'Normal'
 'Normal' 'Normal' 'Normal' 'Ringan' 'Normal' 'Normal' 'Normal' 'Normal'
 'Normal' 'Ringan' 'Normal' 'Normal']
Confusion Matrix:
[[12  0  0]
 [ 4  0  0]
 [ 0  2  2]]
              precision    recall  f1-score   support

      Normal       0.75      1.00      0.86        12
      Ringan       0.00      0.00      0.00         4
      Sedang       1.00      0.50      0.67         4

    accuracy                           0.70        20
   macro avg       0.58      0.50      0.51        20
weighted avg       0.65      0.70      0.65        20

akurasi: 
0.7
