In [1]:
#Import necessary modules
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

df = pd.read_csv("stress1.csv", sep=";")
#print(df)

# Create feature and target arrays
X = df[['S1','S2','S3','S4','S5','S6','S7']]
y = df['tingkat_stres']
  
# Split into training and test set
X_train, X_test, y_train, y_test = train_test_split(
             X, y, test_size = 0.2, random_state=42)

print(y_test)
  
knn = KNeighborsClassifier(n_neighbors=7)
  
knn.fit(X_train, y_train)

# Predicting the Test set results
y_pred = knn.predict(X_test)
print('Hasil Prediksi:')
print(knn.predict(X_test))

# membuat confusion matrix
confusion_matrix(y_test, y_pred)
print('Confusion Matrix:')
print(confusion_matrix(y_test, y_pred))

#evaluate performance from the confusion matrix 
from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(y_test, y_pred))
  
# Calculate the accuracy of the model
print('akurasi: ')
print(knn.score(X_test, y_test))

83    Ringan
53    Normal
70     Berat
45    Normal
44    Ringan
39    Normal
22    Ringan
80    Ringan
10    Sedang
0     Ringan
18    Normal
30    Ringan
73    Normal
33    Normal
90    Ringan
4     Normal
76    Normal
77    Sedang
12    Ringan
31    Normal
Name: tingkat_stres, dtype: object
Hasil Prediksi:
['Ringan' 'Normal' 'Berat' 'Normal' 'Normal' 'Normal' 'Ringan' 'Ringan'
 'Sedang' 'Ringan' 'Normal' 'Sedang' 'Normal' 'Normal' 'Ringan' 'Normal'
 'Normal' 'Sedang' 'Sedang' 'Normal']
Confusion Matrix:
[[1 0 0 0]
 [0 9 0 0]
 [0 1 5 2]
 [0 0 0 2]]
              precision    recall  f1-score   support

       Berat       1.00      1.00      1.00         1
      Normal       0.90      1.00      0.95         9
      Ringan       1.00      0.62      0.77         8
      Sedang       0.50      1.00      0.67         2

    accuracy                           0.85        20
   macro avg       0.85      0.91      0.85        20
weighted avg       0.91      0.85      0.85        20

akurasi: